export enum actionTypes {
    LOADING_AUTH = 'LOADING_AUTH',
    LOGIN = 'LOGIN',
    LOGIN_SUCCESS = 'LOGIN_SUCCES',
    LOGIN_ERROR = 'LOGIN_ERROR',

    REGISTRATION = 'REGISTRATION',
    REGISTRATION_SUCCESS = 'REGISTRATION_SUCCES',
    REGISTRATION_ERROR = 'REGISTRATION_ERROR',

    LOGOUT = 'LOGOUT',
}